logging:
  level:
    root: INFO
    dev.mbo: TRACE
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
  port: 8080
  address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: GET

spring:
  application:
    name: metrics
  main:
    banner-mode: off
  profiles:
    active: secure
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: s3cr3t
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 3300000
      connection-init-sql: SELECT 1
      connection-test-query: ${spring.datasource.hikari.connection-init-sql}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        generate_statistics: true
    show-sql: false
  jackson:
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_INVALID_SUBTYPE: false
    serialization:
      INDENT_OUTPUT: false
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_EMPTY_JSON_ARRAYS: false
      WRITE_ENUMS_USING_TO_STRING: true
      WRITE_NULL_MAP_VALUES: false
      WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED: false
      FAIL_ON_SELF_REFERENCES: true
    default-property-inclusion: non_null
    time-zone: UTC
