# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - '/etc/prometheus/prometheus.rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alert-manager:9093"

scrape_configs:
  - job_name: 'postgresql'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:9187' ]
        labels:
          type: container
          category: infra
  - job_name: metrics-service
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
        'host.docker.internal:8080',
      ]
        labels:
          type: kotlin
          framework: springboot
          category: service
